Add RSpec model/request tests to rails preset
otavioschwanck/telescope-alternate.nvim pull request #4
Opened 2022-09-25 23:26 UTC by jonathan-raines

Added Rspec model and request tests to the Rails present for models and controllers

2022-09-25 23:33 UTC, otavioschwanck commented
> Added Rspec model and request tests to the Rails present for models and controllers

maybe you could add this globally:

{ "app/(.*).rb", { { "spec/[1]_spec.rb", "Test" } },
{ "spec/(.*).rb", { { "app/[1]_spec.rb", "Original" } }

2022-09-25 23:38 UTC, otavioschwanck commented on lua/telescope-alternate/presets.lua
> +    { 'spec/requests[1]/[2]*_spec.rb', 'Request Test' },
Leave all spec relates to the rspec preset.  So who uses minitest can do differently

2022-09-25 23:39 UTC, otavioschwanck requested changes

2022-09-25 23:39 UTC, otavioschwanck commented on lua/telescope-alternate/presets.lua
> +  { 'app/models/(.*).rb', {
Maybe something like that?

{ "app/(.*).rb", { { "spec/[1]_spec.rb", "Test" } },
{ "spec/(.*).rb", { { "app/[1]_spec.rb", "Original" } }

And about the request tests, maybe is more relate to the controller only.

2022-09-25 23:45 UTC, jonathan-raines commented
Yeah I was starting to think an rspec preset would be better. I will get to work on it

2022-09-26 01:54 UTC, jonathan-raines commented
This more verbose than I'd like. Rspec considers `spec/controllers` to be obsolete to `spec/requests`, which doesn't play nice with the wildcard regex. I've been trying to figure out to have one preset that excludes controllers, which would generate most of the needed alternate files, then another preset specifically to handle the `controllers -> requests` & `requests -> controllers` case.

If you have any ideas, please let me know!

2022-09-26 10:30 UTC, otavioschwanck requested changes

2022-09-26 10:30 UTC, otavioschwanck commented on lua/telescope-alternate/presets.lua
> +}
```suggestion
M.rspec = {
  { "app/(.*).rb", { { "spec/[1]_spec.rb", "Test" } } },
  { "app/controllers/(.*)_controller.rb", {
    { "spec/requests/[1]_spec.rb", "Request Test" }
  } },
  { "spec/requests/(.*)_spec.rb", {
    { "app/controllers/[1]_controller.rb", "Controller Test" },
  } },
}
```

2022-09-26 11:50 UTC, jonathan-raines commented
The only issue I see with this implementation is going from a controllers test back to the original. `{ 'spec/(.*)_spec.rb', { { 'app/[1].rb', 'Original' } } }` catches and provides option for a new Original file for `app/requests/...`.

<img width="867" alt="image" src="https://user-images.githubusercontent.com/5840124/192269141-03fe3846-c5cc-498b-862a-a5c9da0c8ec0.png">

2022-09-26 12:09 UTC, otavioschwanck commented
> The only issue I see with this implementation is going from a controllers test back to the original. `{ 'spec/(.*)_spec.rb', { { 'app/[1].rb', 'Original' } } }` catches and provides option for a new Original file for `app/requests/...`.
> 
> <img alt="image" width="867" src="https://user-images.githubusercontent.com/5840124/192269141-03fe3846-c5cc-498b-862a-a5c9da0c8ec0.png">
> 
> The verbose implementation doesn't encounter that, but it is more verbose lol

i understand your point, but with the more generic approach, we can use other structures, like on my company, we have cells/ and business/.

So i think is ok to have the new there, the NEW is always above the matches

2022-09-26 12:09 UTC, merged

2022-09-26 12:33 UTC, otavioschwanck commented
@jonathan-raines thanks for your contribution!